### ISSUE TITLE
Gulp Error

### ISSUE THREAD

**Issue by jerimiahmilton** [tylerl0706/project-lightning#11]
After cloning the repo, I run `npm install` then `gulp` and I get the following error message.

```boltly master % gulp
[13:07:33] Using gulpfile ~/Development/boltly/gulpfile.js
[13:07:33] Starting 'js'...
[13:07:33] 'js' errored after 8.63 ms
[13:07:33] ReferenceError: ngAnnotate is not defined
    at Gulp.gulp.task (/Users/isapple/Development/boltly/gulpfile.js:80:9)
    at module.exports (/Users/isapple/Development/boltly/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/isapple/Development/boltly/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/isapple/Development/boltly/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/isapple/Development/boltly/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:46:20
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)```

**Comment by TylerLeonhardt** [comment]
What does:

`npm start`

Give you?

It's been a while since I've touched this repo

**Comment by TylerLeonhardt** [comment]
Can you try grabbing latest, I rolled back a few commits that might have been the culprit. Let me know if it works for you

**Comment by TylerLeonhardt** [comment]
Also keep in mind the prereq section of the README
